### ISSUE TITLE
Running page 70005 gives error if replace reports is set

### ISSUE THREAD

**Issue by JohnvanPoelgeest** [ReportsForNAV/Beta#21]
When running page 70005 and selecting "replace reports" the following error is given:

"There is no Object within the filter.
Filters: Type: Report, Name: ForNAV Sal. Order Confirmation"

Running without "Replace reports" does not give an error, but where are the reports?

Running NAV 2017 NL build 10.0.16585.0 (CU6), reportsForNav 2.0.0.1220

![fornavbeta_convert_step1](https://cloud.githubusercontent.com/assets/28647178/25992449/d81288e8-3706-11e7-802b-0e6c41563dc9.png)
![fornavbeta_convert_step2](https://cloud.githubusercontent.com/assets/28647178/25992452/db1796dc-3706-11e7-8a70-0614a971557d.png)
![fornavbeta_convert_step3](https://cloud.githubusercontent.com/assets/28647178/25992458/e0ec9d46-3706-11e7-9205-053e7aeef093.png)
![fornavbeta_convert_step4](https://cloud.githubusercontent.com/assets/28647178/25992470/e5ea7318-3706-11e7-9da4-53802b31db71.png)
![fornavbeta_convert_step5](https://cloud.githubusercontent.com/assets/28647178/25992476/e89e143e-3706-11e7-953e-fdb1218181f3.png)

**Comment by ReportsForNAV** [comment]
Thanks for reporting this issue John. It has been fixed and we will send out a new version soon with more improvements.

**Comment by ReportsForNAV** [comment]
Fixed in the May Release
