### ISSUE TITLE
"Copy of" (RG)

### ISSUE THREAD

**Issue by ReportsForNAV** [ReportsForNAV/Beta#45]
I cannot see how far the „Copy of“ version is implemented. In this context there is a problem when trying to print a larger number of copies. I don’t know how you calculate this, but it seems that the number of copies is calculated by the formula 1+n! . With 4 copies you get 11 pages 1 original + 1+2+3+4 = 10 pages as copies. When you have that „legal garbage“ at the bottom it is sometimes printed on the correct page, sometimes on a separate page. The text „Copy“ ist essential, i.e. it must be printed.

**Comment by markbrummel** [comment]
Same as #6
