### ISSUE TITLE
No need to print subtotals when the VAT is zero (RG)

### ISSUE THREAD

**Issue by ReportsForNAV** [ReportsForNAV/Beta#47]

**Comment by afromazzoni** [comment]
do what you would have done in the classic client use two different footers and the ShowOutput property.

**Comment by markbrummel** [comment]
We've made a decision to keep the reports as simple as possible and it's fairly easy to make the VAT behave as you describe as a small mod.

Our idea is to ship a frequently asked modifications How Do I library with descriptions and videos.
