### ISSUE TITLE
Trial Balance Issues (Amanda)

### ISSUE THREAD

**Issue by markbrummel** [ReportsForNAV/Beta#65]
1.	Trial Balance 
b.	Period & Filter seem to be redundant information. I’d remove the date information from the Filter.
d.	When running filtered on Type: Posting there are additional spaces between a few of the accounts at the end which need to be removed
f.	Is there a TB in the WW database that shows the balance of accounts in one column with credits shown as negative? If so, I think that would be a beneficial format of this report as well.

**Comment by ExtVaMyk** [comment]
"ForNAV Trial Balance" report will be replaced with another version, based on NA, not WW.
