### ISSUE TITLE
Salesperson – Commission (Amanda)

### ISSUE THREAD

**Issue by markbrummel** [ReportsForNAV/Beta#67]
3.	Salesperson – Commission 
b.	What is Adjusted Profit calculated on? It’s the same for all columns in the data so I’m not sure what it should be.
c.	There is an error on the final page of this report

**Comment by ExtVaMyk** [comment]
Adjusted Profit was inherited from WW version. Its purpose is to show a profit calculated after cost adjustments. Since it's not working very well e.g. with resources  - these two columns will be removed.
