### ISSUE TITLE
Aged Accounts Receivable (Amanda)

### ISSUE THREAD

**Issue by markbrummel** [ReportsForNAV/Beta#68]
4.	Aged Accounts Receivable 
c.	The footer information on the bottom is good, but it wraps around instead of extending to the right margin
d.	The page marker (1/2 – 2/2) also does not extend to the right margin
e.	There’s a fair amount of white space on page 1 between the filters and the beginning of the data. If you can reduce that, it would be good.
f.	It defaults to landscape. If it could be set on portrait and still fit everything that might help some of the other issues mentioned above.
g.	Change “Currency Total” to “Currencies Totals”
h.	Change “Print Amounts in LCY:” to “Print Amounts in Customer’s Currency”
i.	If possible, allow number of buckets to be defined by the user (up to 5).
j.	There is an error on the final page of this report

**Comment by ExtVaMyk** [comment]
Footer/header, and whitespaces, and captions, and error messages issues are solved.
Number of columns and landskape/portrait are the subject of new enchancement.
