### ISSUE TITLE
Aged Accounts Payable  (Amanda)

### ISSUE THREAD

**Issue by markbrummel** [ReportsForNAV/Beta#69]
5.	Aged Accounts Payable 
c.	Replicate the footer information on the bottom like the Aged Receivables
d.	The page marker (1/2 – 2/2) also does not quite extend to the right margin
e.	There’s a fair amount of white space on page 1 between the filters and the beginning of the data. If you can reduce that, it would be good.
f.	When this report is one page long, the Currency totals go to a second page, even though there is space on the first page.
g.	Change “Currency Specifications” to “Currencies Totals”
h.	Change “Print Amounts in LCY:” to “Print Amounts in Customer’s Currency”
i.	If possible, allow number of buckets to be defined by the user (up to 5).
j.	There is an error on the final page of this report

**Comment by ExtVaMyk** [comment]
Footer/header issue solved, whitespace too.
Totals are on the separate last page if "New page per Vendor" property applied from request page.
Captions changed.
Error meesages checked and solved.
