### ISSUE TITLE
Extra margin when using watermarks.

### ISSUE THREAD

**Issue by ExtVaMyk** [ReportsForNAV/Beta#72]
In some environments there is an extra margin added to a watermark.
![image](https://user-images.githubusercontent.com/29860562/30031356-b0e72f88-9199-11e7-8288-dec89acc195c.png)
vs 
![image](https://user-images.githubusercontent.com/29860562/30031369-bc509936-9199-11e7-9b51-e11adb02e1a1.png)

**Comment by markbrummel** [comment]
Fixed in new build.
